repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    args: [--strict]
    additional_dependencies: [
      types-requests>=2.31.0,
      pydantic>=2.5.0,
      langchain>=0.3.20,
      langchain-core>=0.1.22,
      langchain-community>=0.3.20,
      langgraph>=0.3.0,
      langgraph_swarm>=0.0.3,
      environs>=14.1.1,
      python-Levenshtein==0.27.1,
      annotated-types>=0.6.0,
      rich>=13.9.4,
      langsmith>=0.2.1,
    ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
