repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint
        entry: make lint
        language: system
        pass_filenames: false
        types: [python]

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: make format
        language: system
        pass_filenames: false
        types: [python]

  - repo: local
    hooks:
      - id: mypy
        name: mypy type checking
        entry: make type
        language: system
        pass_filenames: false
        types: [python]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: make pylint
        language: system
        pass_filenames: false
        types: [python]

  - repo: local
    hooks:
      - id: uv-pip-check
        name: uv pip check
        entry: uv pip check
        language: system
        pass_filenames: false
        always_run: true
