version: '3.8'

services:
  langgraph:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2024:2024
    volumes:
      - .:/app
    environment:
      - LANGSMITH_TRACING=true
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com
    command: ["langgraph", "dev", "--host", "0.0.0.0"]
